services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=/api
      - NODE_ENV=development
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CORS_ORIGIN=http://localhost
      - DEBUG=true
    networks:
      - app-network
  monitoring-agent:
    build:
      context: ./python-agent
      dockerfile: Dockerfile
    container_name: server-monitoring-agent
    environment:
      - SERVER_NAME=Production Server
      - SERVER_LOCATION=US East
      - API_ENDPOINT=http://backend:3001/api/metrics
      - API_KEY=sk_cc549fac-2467-4c51-96eb-a87c24f03096
      - INTERVAL=60
      - DEBUG=false
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "server_monitor.py", "--test"]
      interval: 60s
      timeout: 30s
      retries: 3

networks:
  app-network:
    driver: bridge
